//! Imported Bindings from C Header
//!
//! This file imports types from `tb_client.h` using `bindgen` in the `build.rs` file and
//! autogenerated bindings from `rust_bindings.zig`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/// Tigerbeetle Client C Types
pub mod tb_client {
    include!(concat!(env!("OUT_DIR"), "/tb_client.rs"));
}

mod bindings;

pub use bindings::*;
